apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: externaljobs.jobs.example.org
spec:
  group: jobs.example.org
  names:
    kind: ExternalJob
    plural: externaljobs
  scope: Namespaced
  conversion:
    strategy: Webhook
    webhookClientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwakNDQWJxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFhTVJnd0ZnWURWUVFERXc5M1pXSm8KYjI5ckxXTmxjblF0WTJFd0hoY05NVGt3TWpBNU1USTBNREE0V2hjTk1qa3dNakEyTVRJME1EQTRXakFhTVJndwpGZ1lEVlFRREV3OTNaV0pvYjI5ckxXTmxjblF0WTJFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3CmdnRUtBb0lCQVFDM2ZUaXAvNmxiWDNIb3NZRFUvR2plMzROazlHZTNtcU41TFVHUTVQOVFvT2JHdEtFTENKSWkKVU1zUUdWR2x5YnRjYld4UWZTdmxOSGVaeGs1QlNzYmo2VFMvUC83OHNoMEU2RWtlemkzRDhKVUltRDBDTU1hegp0em9CbVRDaHB5QnJUaUdBU1k5OVJlTVlmK2ZaM3EzWWtIOVFuTUVMWCsyOWZ5TVNkTkF5YzRwbkI5SHFDREZNCnJReEFOUXFJU0IycU1rOVpmRHFJb3BpZXdhSXM2Qnl0OG5sNjVkcnUzMzVBVzdhaUZBNGpwMC9vaFY1TVJmMVoKNnk5ZmQ1cmRBS2pqUUdseEVmYUx2UytPazRFRlNaYXVMRWRCb0NRY2lVRXgzWE9Pc2lVSUFTY3BmMENjeTUzdApBejdDRTVQN2NpbjBQN0dXU0hGeVQ5L3ZQN1V4bCtndEFnTUJBQUdqSXpBaE1BNEdBMVVkRHdFQi93UUVBd0lDCnBEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWhCVkZQL3BKajA4emEKQkRsb0RxZFBtdzBxYWRQdVgyY1RESndvVElnTVhYdGVjWlh4eFdzWkQrbjczMlQ2d0syV0dROUFNemhpQ0ZVYwppNVkxSkUrSmJBbWkzNzdBdFdFbWllb1FxUTBpdHRlcWFUcWVsMG5IdlRzL2RsTHYzbWZ0VjJIb1NpTDR3anhzCkN3cCtRWXVYMmxIaDdDckRHeHIzWlJ5bCttbXBOQ211cmtDZ0dBWFBHc3FydW1ZYkREeXVsaXRCNDVsdTVlQnkKcU1TdkwzT3ZabGEvOE9QVDJzZ1N4WTZvdmJRWTA3UzBsTmNKVnJqWmo2T29LTmc2OFdINXB0TXJPOTI2RENJegpnYVhyT3BsVG10NmZNS2xRYzhHWnpJWG11cmpTVFFGNXh3a0tOS1E0MlNleHBJbFV1MndtQ3JzckNpcG1HUW9HCjIrN3NFZlhnCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: crd-cc-webhook-service
        namespace: crd-cc-system
        path: /convert
  versions:
   - name: v1
     served: true
     storage: true
   - name: v2
     served: true
     storage: false
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
